import re

with open("src/lib/exportUtils.ts", "r") as f:
    content = f.read()

# Replace the PDF header style
old_style_header_h1 = ".pdf-header h1 { text-align: center; color: #111; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; font-size: 24px; }"
new_style_header_h1 = ".pdf-header { display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid #000; padding-bottom: 15px; margin-bottom: 25px; }\n      .pdf-header-left { display: flex; align-items: center; gap: 15px; }\n      .pdf-logo { width: 40px; height: 40px; background-color: #000; border-radius: 6px; display: flex; align-items: center; justify-content: center; }\n      .pdf-logo span { color: #fff; font-family: ui-serif, Georgia, Cambria, \"Times New Roman\", Times, serif; font-size: 24px; font-weight: bold; line-height: 1; }\n      .pdf-header-title { text-align: left; }\n      .pdf-header-title h1 { color: #111; font-size: 24px; margin: 0 0 4px 0; border-bottom: none; padding-bottom: 0; }\n      .pdf-header-title p { color: #555; font-size: 12px; margin: 0; }"

content = content.replace(old_style_header_h1, new_style_header_h1)
content = content.replace(".pdf-header p { text-align: right; color: #555; margin-bottom: 30px; font-size: 14px; }", "")

old_html_header = """      <div class="pdf-header">
        <h1>${title}</h1>
        <p>Date: ${new Date().toLocaleDateString()}</p>
      </div>"""

new_html_header = """      <div class="pdf-header">
        <div class="pdf-header-left">
          <div class="pdf-logo">
            <span>L</span>
          </div>
          <div class="pdf-header-title">
            <h1>${title}</h1>
            <p>Generated by Legal Advisories</p>
          </div>
        </div>
        <div style="text-align: right;">
          <p style="color: #555; font-size: 14px; margin: 0;">Date: ${new Date().toLocaleDateString()}</p>
        </div>
      </div>"""

content = content.replace(old_html_header, new_html_header)

with open("src/lib/exportUtils.ts", "w") as f:
    f.write(content)
print("Updated exportUtils.ts")
