import re

with open("src/lib/exportUtils.ts", "r") as f:
    content = f.read()

# Replace flex layout with robust table layout for html2pdf compatibility
old_style_header = """      .pdf-header { display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid #000; padding-bottom: 15px; margin-bottom: 25px; }
      .pdf-header-left { display: flex; align-items: center; gap: 15px; }
      .pdf-logo { width: 40px; height: 40px; background-color: #000; border-radius: 6px; display: flex; align-items: center; justify-content: center; }
      .pdf-logo span { color: #fff; font-family: ui-serif, Georgia, Cambria, "Times New Roman", Times, serif; font-size: 24px; font-weight: bold; line-height: 1; }
      .pdf-header-title { text-align: left; }
      .pdf-header-title h1 { color: #111; font-size: 24px; margin: 0 0 4px 0; border-bottom: none; padding-bottom: 0; }
      .pdf-header-title p { color: #555; font-size: 12px; margin: 0; }"""

new_style_header = """      .pdf-header-table { width: 100%; border-bottom: 2px solid #000; padding-bottom: 15px; margin-bottom: 25px; }
      .pdf-header-table td { padding: 0; vertical-align: middle; border: none; }
      .pdf-logo { width: 40px; height: 40px; background-color: #000; border-radius: 6px; text-align: center; line-height: 40px; }
      .pdf-logo span { color: #fff; font-family: ui-serif, Georgia, Cambria, "Times New Roman", Times, serif; font-size: 24px; font-weight: bold; }
      .pdf-header-title h1 { color: #111; font-size: 24px; margin: 0 0 4px 0; border-bottom: none; padding-bottom: 0; }
      .pdf-header-title p { color: #555; font-size: 12px; margin: 0; }"""

content = content.replace(old_style_header, new_style_header)

old_html_header = """      <div class="pdf-header">
        <div class="pdf-header-left">
          <div class="pdf-logo">
            <span>L</span>
          </div>
          <div class="pdf-header-title">
            <h1>${title}</h1>
            <p>Generated by Legal Advisories</p>
          </div>
        </div>
        <div style="text-align: right;">
          <p style="color: #555; font-size: 14px; margin: 0;">Date: ${new Date().toLocaleDateString()}</p>
        </div>
      </div>"""

new_html_header = """      <table class="pdf-header-table">
        <tr>
          <td style="width: 50px;">
            <div class="pdf-logo">
              <span>L</span>
            </div>
          </td>
          <td class="pdf-header-title">
            <h1>${title}</h1>
            <p>Generated by Legal Advisories</p>
          </td>
          <td style="text-align: right;">
            <p style="color: #555; font-size: 14px; margin: 0;">Date: ${new Date().toLocaleDateString()}</p>
          </td>
        </tr>
      </table>"""

content = content.replace(old_html_header, new_html_header)

with open("src/lib/exportUtils.ts", "w") as f:
    f.write(content)
print("Updated exportUtils.ts for robust table rendering.")
